/**
 * # secret
 *
 * A secret is a securely-stored piece of information,
 * in our case a string. Things like database credentials,
 * oauth secrets, etc should be stored as a secret. In general,
 * secrets are added to running containers via environment variables.
 *
 * Instead of using AWS Secret Manager secrets, we use SSM Parameters,
 * as there is a cost associated with secrets.
 */

locals {
  secret_name = "/${var.project_name}/${var.application_type}-${var.environment != "" ? "${var.environment}-" : "" }${var.name}"
}

resource "random_password" "password" {
  length           = var.length
  special          = true
  override_special = "!#$-"
}


resource "aws_ssm_parameter" "this" {
  name     = local.secret_name
  type     = "SecureString"
  value    = var.value == null ? random_password.password.result : var.value
  tags = {
    project = var.project_name
  }

  lifecycle {
    ignore_changes = [ value ]
  }
}

output "arn" {
  value = aws_ssm_parameter.this.arn
  description = "the ARN of the generated ssm parameter"
}

output "value" {
  value = random_password.password.result
  sensitive = true
  description = "value of autogenerated secret"
}

